### ISSUE TITLE
Disable Menu Elements

### ISSUE THREAD

**Issue by jb-cloud** [zerostaticthemes/hugo-winston-theme#38]
Is it possible to choose the top right menu options? For example disable the blog or about sections?

**Comment by onthedock** [comment]
If you want to remove the "About" page from the menu, you can remove the `content/pages/about.md` file.
If you want to add additional "pages", you can add additional files to the `content/pages/` folder. Make sure you include the required metadata (e.g. `me.md`):

```yaml
---
title: 'Me'
image: images/author.jpg
url: "me"
menu:
  main:
    name: "Me"
    weight: 0
---

Hi, it's me!
```

Not sure if there's a way to enable/disable the `About` page from the `config.toml` file.

To remove the "Blog" entry, remove (or rename) the `content/posts/_index.md` file.

Hope it helps!

Xavi
