### ISSUE TITLE
Bulleted lists do not comply with left margin on mobile (tested on iOS)

### ISSUE THREAD

**Issue by isaacverdu** [zerostaticthemes/hugo-winston-theme#48]
First of all, thanks a lot for making (and supporting) this theme for free. The references to 1984 resonated with me :-)

The issue: bulleted lists align to the left in mobile (iOS), disregarding the padding/margins that the rest of the text adheres to. Here it is ion my website:

![Image](https://github.com/user-attachments/assets/9514b34e-8d04-4cdf-b272-7ade48f71fc1)

Here it is in the live demo:

![Image](https://github.com/user-attachments/assets/8dd3cc35-e805-4c60-8858-0a1406d21052)

Thanks!

Isaac

**Comment by anonfaded** [comment]
I have done a workaround, which can work for you as well. 
In the `static/css` folder, make a `custom.css` file, and in that paste the following code, this will overwrite the default styling values:

```css
/* Bullet points styling */
.content ul,
.content ol {
  margin-left: 20px !important;
  margin-top: 10px !important;
  margin-bottom: 20px !important;
}

.content ul li,
.content ol li {
  font-size: 18px !important;
  line-height: 20px !important;
  margin-bottom: 10px !important;
  margin-left: 20px !important;
}

@media (max-width: 767px) {
  .content ul,
  .content ol {
    margin-left: 15px !important;
    padding-right: 15px !important;
  }
  
  .content ul li,
  .content ol li {
    margin-left: 15px !important;
    margin-bottom: 8px !important;
    line-height: 1.5 !important;
  }
}
``` 

It will be better to use some Ai code editor like Windsurf or cursor, which can do this easily for you if you are not familiar with coding much.

## Demo:

![Image](https://github.com/user-attachments/assets/c93044ca-d297-4d07-bf35-1e0d8fa2b1f7)
